import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
    <head>
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet"/>
    </head>
    <body className={inter.className}>
    <div className="bg-vera text-vera border-vera hidden"></div>
    <div className="bg-dark-vera hidden"></div>
    <div className="bg-regio text-regio border-regio hidden "></div>
    <div className="bg-dark-regio hidden"></div>
    {children}
    </body>
    </html>
  );
}
